---
title: "Week 1 worksheet: Introduction to R (part 1)"
output: html_document
---

# Introduction
Attempt to complete the following exercises based on week 1 teaching materials. A zoom meeting will be held on the 23rd of April where a course coordinator will walk through the worksheet and subsequently post the completed worksheet to github for those unable to attend the zoom conference. 

# Part 1
A randomn vector has been generated for you, sampling 100 numbers between 1 and 100 with replacement. set.seed() is used to make sure the same 100 numbers are generated for all participants..
```{R Part 1}
set.seed(11384191) #do not change!

vector <- sample(1:100, 100, replace=TRUE)

# [1] 
# Confirm the length of the vector is 100
length(vector)

# [2] 
# Use the unique() function to print the unique numbers
unique(vector)

# [3] 
# Combine length() and unique() to print the number of unique numbers in the vector
length(unique(vector))

# [4] 
# Print the last item in the vector
len <- length(vector)
print(vector[len])

# [5] 
# Print the 20th to 30th elements in the vector
vector[20:30]
```

# Part 2
You will need to use for loops, conditional statements and comparison operators to complete this exercise. 
```{R}
# [1] 
# Create a for loop to print every item in the vector
for(i in vector){
  print(i)
}

# [2] 
# Using a for loop to iterate over every item in the vector, add an if..else statement to check if values are 
# above or below 50. Recall that comparison operators return TRUE if the condition is satisfied, if the condition 
# is not satisfied the else code block is executed. If values are above 50, use the combine function to add them
# to the vector 'above_50'. If not, add the value to 'below_50' vector.


# Two empty vectors have been initialised for you:
above_50 <- c()
below_50 <- c()

for(i in vector){
    if(i > 50){
      above_50 <- c(above_50, i) 
    } else{
      below_50 <- c(below_50, i)
    }
}

# [3] 
# Find the number of items in above_50 and below_50
length(above_50)
length(below_50)

# [4] 
# Find the fraction of items that are above 50 & below 50 (using the original vector as the denominator)
length(above_50)/length(vector)
length(below_50)/length(vector)
```

# Part 3 
In this excercise we are going to mimick visiting 18+ websites (to buy alcohol, of course..) and create code that checks a users D.O.B
We will build up the code as we go along.
```{R}
# [1]
# Use an if..else statement to check if the variable 'age' is above or below 18
# If under 18, print "You are not old enough to purchase alcohol"
# If 18+, print "Entering website"

age <- 18
  
if(age < 18){
  print("You are not old enough to purchase alcohol")
  } else{
  print("Entering website")
}

# [2]
# In the first part, we had to create the variable age. 
# This time we will use the "readline" function in R to promt user input in the console
# (the console is the bottom left box in R Studio) and assign it to age
# Recreate the last if..else loop using this new age variable

age <- readline(prompt = "Please Enter Your Age: ")

if(age < 18){
  print("You are not old enough to purchase alcohol")
} else{
  print("Entering website")
}

# [3]
# Lets make our readlines function a little more realistic. 
# We will ask the user to enter their date of birth in the format: YYYY-MM-DD
# Change the promt to: "Please Enter Your Age \nUse format YYYY-MM-DD: "
# Wrap the readlines function in the 'as.Date()' function. 
# This will let R know it is a date, not a character string. 

age <- as.Date(readline(prompt = "Please Enter Your Age \nUse format YYYY-MM-DD: "))

# [4]
# Convert the variable age to a numeric. It will output the Date into days. 
# Reproduce part [2] with your new prompt function, making sure to convert the
# age variable to a numeric. hint 18 years = 6570 days..

age <- as.Date(readline(prompt = "Please Enter Your Age \nUse format YYYY-MM-DD: "))

age <- as.numeric(age)

if(age < 6570){
  print("You are not old enough to purchase alcohol")
} else{
    print("Entering Website")
  }
}
```

# Part 4
Here we will mimick calculating Fold Change for 10 simulated genes in 2 samples using lists. Data has been generated for you and stored in sample_1 an sample_2 lists respectively. 


## Note to self: Add comments and build up how to calc Fold Change (reciprocal if < 1).. 
## Create function to calculate recip?
```{R}
set.seed(11384191)
sample_1 <- list(sample(runif(10, 0, 1000)))
sample_2 <- list(sample(runif(10, 0, 1000)))

names(sample_1) <- "treatment"
names(sample_2) <- "control"

fold_change_vector <- c()

for(i in length(sample_1)){
  ratio <- (sample_1[[i]]) / (sample_2[[i]])
  if(ratio > 1){
    fold_change <- ratio
  } else{
    fold_change <- 1/ratio
  }
  
  fold_change_vector <- c(fold_change_vector, fold_change)
}

print(fold_change_vector)

LFC <- log2(fold_change_vector)
```
